version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: fast-shoppers
      MYSQL_DATABASE: fast-shoppers-db
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"