name: Test CI

on:
  pull_request:
    branches:
      - main
      - feature/*
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradle 명령 실행을 위해 권한 부여
        run: chmod +x ./gradlew

      - name: 그래들 build
        run: ./gradlew build -Pprofile=test

      - name: 테스트 실행
        run: ./gradlew test -Pprofile=test

      - name: 테스트 결과 저장
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

      - name: 코멘트 추가 (테스트 성공)
        uses: unsplash/comment-on-pr@v1.3.0
        if: success()
        with:
          msg: '테스트 성공!'
          check_for_duplicate_msg: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 코멘트 추가 (테스트 실패)
        uses: unsplash/comment-on-pr@v1.3.0
        if: failure()
        with:
          msg: '테스트 실패: 원인을 확인하세요.'
          check_for_duplicate_msg: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
